# Generated by Django 4.1.7 on 2023-04-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empt',
            fields=[
                ('EmpNo', models.IntegerField(primary_key=True, serialize=False)),
                ('EName', models.CharField(max_length=100, unique=True)),
                ('Job', models.CharField(max_length=100)),
                ('Mgr', models.IntegerField()),
                ('HireDate', models.DateField()),
                ('Salary', models.IntegerField()),
                ('Commission', models.IntegerField()),
                ('DeptNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.depat')),
            ],
        ),
    ]
