# Generated by Django 4.1.7 on 2023-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empt',
            name='Commission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
